# Generated by Django 3.2.9 on 2022-05-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
